user_gateway/config/routes.rb
Rails.application.routes.draw do
  root to: 'worklists#index'
  resources :worklists, only: :index
  resources :worklist_items, except: [:create, :show]
end

user_gateway/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def initialize
    ApplicationController.initialize_rabbitmq
  end

  def self.initialize_rabbitmq
    @rabbit_connection = Bunny.new(host: 'wfms_mom_1')
    @rabbit_connection.start
    @channel = @rabbit_connection.create_channel
    @topic = @channel.topic('wfms', durable: true)
  end

  def self.channel
    @channel
  end

  def self.topic
    @topic
  end

  def mq_request(key, response_key, payload)
    rq = new_response_queue("wfms.#{response_key}")
    Hutch.publish "wfms.#{key}", payload
    get_response(rq)
  end

  def new_response_queue(key)
    response_queue = ApplicationController.channel.queue("", :exclusive => true)
    response_queue.bind(ApplicationController.topic, routing_key: key)
    response_queue
  end

  def get_response(queue, timeout=10)
    @response_object = nil
    begin
      Timeout::timeout(timeout) do
        queue.subscribe(:block => true) do |delivery_info, properties, body|
          @response_object = JSON.parse(body)
          delivery_info.consumer.cancel
        end
      end
    ensure
      queue.delete
    end
    @response_object
  end
end

user_gateway/app/controllers/worklist_items_controller.rb
class WorklistItemsController < ApplicationController
  def index
    @worklist_items = mq_request 'worklist_item.index', 'worklist_item.indexed', role_id: params[:role_id]
    @worklist_items = @worklist_items['worklist']
  end

  def edit
    @worklist_item = mq_request 'worklist_item.show', 'worklist_item.showed', id: params[:id]
  end

  def update
    mq_request 'worklist_item.update', 'worklist_item.updated', id: params[:id], worklist_item: params[:worklist_item]
    redirect_to worklist_items_url, notice: 'Worklist item was successfully submitted.'
  end

  def destroy
    mq_request 'wfms.user.destroy', 'wfms.user.destroyed', id: params[:id]
    redirect_to worklist_items_url, notice: 'Worklist item was successfully destroyed.'
  end

  private

  def worklist_item_params
    params[:worklist_item]
  end
end

user_gateway/app/controllers/worklists_controller.rb
class WorklistsController < ApplicationController
  def index
    @users = mq_request 'user.index', 'user.indexed', {}
  end
end

user_gateway/app/helpers/application_helper.rb
module ApplicationHelper
end

user_gateway/app/helpers/worklist_items_helper.rb
module WorklistItemsHelper
end

user_gateway/app/helpers/worklists_helper.rb
module WorklistsHelper
end

user_gateway/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UserGateway
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

user_gateway/app/views/worklist_items/_form.html.haml
= form_for @worklist_item do |f|
  - if @worklist_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@worklist_item.errors.count, "error")} prohibited this worklist_item from being saved:"
      %ul
        - @worklist_item.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

user_gateway/app/views/worklist_items/edit.html.haml
%h1 Editing worklist_item

= render 'form'

= link_to 'Show', @worklist_item
\|
= link_to 'Back', worklist_items_path

user_gateway/app/views/worklist_items/index.html.haml
%h1 Worklist items

%table
  %thead
    %tr
      %th

  %tbody
    - @worklist_items.each do |item|
      %tr
        %td= item